name: ASCII Artwok

on: workflow_dispatch

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Install Cowsay program
              run: sudo apt-get install cowsay -y
            
            - name: List repo files
              run: ls -ltra

            - name: Running Shell Script
              run: | 
               chmod +x myscript.sh 
               ./myscript.sh
            
            #- name: Run Cowsay Command
            #  run: cowsay -f dragon "I am a Dragon, FIRE!!!!!!" >> dragon.txt

            #- name: Check file
            #  run: grep -i "dragon" dragon.txt
 
            #- name: Read file
            #  run: cat dragon.txt
            
            #- name: Checkout repo
            #  run: ls -ltra
            


